<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'category_id' => 1,
                'name' => 'Laptop',
                'slug' => 'laptop',
                'description' => 'Un laptop plutôt cool',
                'price' => 1200.00,
                'stock' => 255,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Smartphone',
                'slug' => 'smartphone',
                'description' => 'Téléphone intelligent dernière génération',
                'price' => 899.99,
                'stock' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Tablette',
                'slug' => 'tablette',
                'description' => 'Tablette tactile haute performance',
                'price' => 499.99,
                'stock' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Casque Bluetooth',
                'slug' => 'casque-bluetooth',
                'description' => 'Casque sans fil avec réduction de bruit',
                'price' => 199.90,
                'stock' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Montre connectée',
                'slug' => 'montre-connectee',
                'description' => 'Smartwatch avec suivi d’activité',
                'price' => 249.50,
                'stock' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Clavier mécanique',
                'slug' => 'clavier-mecanique',
                'description' => 'Clavier gamer rétroéclairé RGB',
                'price' => 129.99,
                'stock' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Souris gaming',
                'slug' => 'souris-gaming',
                'description' => 'Souris précise pour joueurs',
                'price' => 59.99,
                'stock' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Écran 27 pouces',
                'slug' => 'ecran-27-pouces',
                'description' => 'Moniteur Full HD 144Hz',
                'price' => 299.00,
                'stock' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Disque dur externe',
                'slug' => 'disque-dur-externe',
                'description' => 'Stockage externe 2To USB 3.0',
                'price' => 89.90,
                'stock' => 140,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Enceinte Bluetooth',
                'slug' => 'enceinte-bluetooth',
                'description' => 'Enceinte portable avec son puissant',
                'price' => 79.99,
                'stock' => 210,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //--------------------------------------------------

            [
                'category_id' => 2,
                'name' => 'Hoodies',
                'slug' => 'hoodies',
                'description' => 'Hoodies de couleur bleu',
                'price' => 39.99,
                'stock' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'T-shirt',
                'slug' => 't-shirt',
                'description' => 'T-shirt en coton blanc',
                'price' => 19.99,
                'stock' => 500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Jean Slim',
                'slug' => 'jean-slim',
                'description' => 'Jean slim fit bleu foncé',
                'price' => 49.90,
                'stock' => 220,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Veste en cuir',
                'slug' => 'veste-cuir',
                'description' => 'Veste en cuir noir pour homme',
                'price' => 149.99,
                'stock' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Chaussures de sport',
                'slug' => 'chaussures-sport',
                'description' => 'Baskets légères et confortables',
                'price' => 79.99,
                'stock' => 140,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Casquette',
                'slug' => 'casquette',
                'description' => 'Casquette ajustable noire',
                'price' => 14.99,
                'stock' => 350,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Pull en laine',
                'slug' => 'pull-laine',
                'description' => 'Pull chaud en laine grise',
                'price' => 59.90,
                'stock' => 130,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Short d’été',
                'slug' => 'short-ete',
                'description' => 'Short léger pour la saison estivale',
                'price' => 24.99,
                'stock' => 260,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Écharpe',
                'slug' => 'echarpe',
                'description' => 'Écharpe douce et chaude',
                'price' => 17.50,
                'stock' => 190,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Gants',
                'slug' => 'gants',
                'description' => 'Gants d’hiver confortables',
                'price' => 12.99,
                'stock' => 210,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //-------------------------------------------------------

            [
                'category_id' => 3,
                'name' => 'Canapé',
                'slug' => 'canape',
                'description' => 'C\'est Canapi !',
                'price' => 807.00,
                'stock' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 3,
                'name' => 'Table basse',
                'slug' => 'table-basse',
                'description' => 'Table basse en bois moderne',
                'price' => 120.50,
                'stock' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Chaise de bureau',
                'slug' => 'chaise-bureau',
                'description' => 'Chaise ergonomique confortable',
                'price' => 199.99,
                'stock' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Lit double',
                'slug' => 'lit-double',
                'description' => 'Lit double en bois massif',
                'price' => 599.00,
                'stock' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Armoire',
                'slug' => 'armoire',
                'description' => 'Grande armoire avec penderie',
                'price' => 450.75,
                'stock' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Bibliothèque',
                'slug' => 'bibliotheque',
                'description' => 'Étagère bibliothèque 5 niveaux',
                'price' => 180.00,
                'stock' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Table à manger',
                'slug' => 'table-manger',
                'description' => 'Grande table pour salle à manger',
                'price' => 650.00,
                'stock' => 55,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Commode',
                'slug' => 'commode',
                'description' => 'Commode en bois avec tiroirs',
                'price' => 275.90,
                'stock' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Meuble TV',
                'slug' => 'meuble-tv',
                'description' => 'Meuble TV design moderne',
                'price' => 320.00,
                'stock' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Fauteuil',
                'slug' => 'fauteuil',
                'description' => 'Fauteuil confortable en tissu',
                'price' => 210.00,
                'stock' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
